@extends('layout')

@section('title', __("AGB"))

@section('description','AGBs der Irion GmbH, Ihrem Partner für Schweißgruppen und CNC Technik.')

@section('head')
    <meta name="robots" content="noindex, follow">
@endsection

@section('content')
<style>
    strong {
        color: #4486c7;
    }
</style>
<section class="container mt-5">
    <p><strong>Allgemeine Lieferbedingungen zur Verwendung gegenüber Unternehmern</strong></p>
    <p><strong>§ 1 Geltung</strong></p>
    <p>(1) Alle Lieferungen, Leistungen und Angebote des Verkäufers erfolgen ausschließlich aufgrund dieser Allgemeinen Lieferbedingungen. Diese sind Bestandteil aller Verträge, die der Verkäufer mit seinen Vertragspartnern (nachfolgend auch „Auftraggeber“ genannt) über die von ihm angebotenen Lieferungen oder Leistungen schließt. Sie gelten auch für alle zukünftigen Lieferungen, Leistungen oder Angebote an den Auftraggeber, selbst wenn sie nicht nochmals gesondert vereinbart werden.</p>
    <p>(2) Geschäftsbedingungen des Auftraggebers oder Dritter finden keine Anwendung, auch wenn der Verkäufer ihrer Geltung im Einzelfall nicht gesondert widerspricht. Selbst wenn der Verkäufer auf ein Schreiben Bezug nimmt, das Geschäftsbedingungen des Auftraggebers oder eines Dritten enthält oder auf solche verweist, liegt darin kein Einverständnis mit der Geltung jener Geschäftsbedingungen.</p>
    <p><strong>§ 2 Angebot und Vertragsabschluss</strong></p>
    <p>(1) Alle Angebote des Verkäufers sind freibleibend und unverbindlich, sofern sie nicht ausdrücklich als verbindlich gekennzeichnet sind oder eine bestimmte Annahmefrist enthalten. Bestellungen oder Aufträge kann der Verkäufer innerhalb von vierzehn Tagen nach Zugang annehmen.</p>
    <p>(2) Allein maßgeblich für die Rechtsbeziehungen zwischen Verkäufer und Auftraggeber ist der schriftlich geschlossene Kaufvertrag, einschließlich dieser Allgemeinen Lieferbedingungen. Dieser gibt alle Abreden zwischen den Vertragsparteien zum Vertragsgegenstand vollständig wieder. Mündliche Zusagen des Verkäufers vor Abschluss dieses Vertrages sind rechtlich unverbindlich und mündliche Abreden der Vertragsparteien werden durch den schriftlichen Vertrag ersetzt, sofern sich nicht jeweils ausdrücklich aus ihnen ergibt, dass sie verbindlich fortgelten.</p>
    <p>(3) Ergänzungen und Abänderungen der getroffenen Vereinbarungen einschließlich dieser Allgemeinen Lieferbedingungen bedürfen zu ihrer Wirksamkeit der Schriftform. Mit Ausnahme von Geschäftsführern oder Prokuristen sind die Mitarbeiter des Verkäufers nicht berechtigt, hiervon abweichende mündliche Abreden zu treffen. Zur Wahrung der Schriftform genügt die telekommunikative Übermittlung, insbesondere per Telefax oder per E-Mail, sofern die Kopie der unterschriebenen Erklärung übermittelt wird.</p>
    <p>(4) Angaben des Verkäufers zum Gegenstand der Lieferung oder Leistung (zB. Gewichte, Maße, Gebrauchswerte, Belastbarkeit, Toleranzen und technische Daten) sowie unsere Darstellungen desselben (zB. Zeichnungen und Abbildungen) sind nur annähernd maßgeblich, soweit nicht die Verwendbarkeit zum vertraglich vorgesehenen Zweck eine genaue Übereinstimmung voraussetzt. Sie sind keine garantierten Beschaffenheitsmerkmale, sondern Beschreibungen oder Kennzeichnungen der Lieferung oder Leistung. Handelsübliche Abweichungen und Abweichungen, die aufgrund rechtlicher Vorschriften erfolgen oder technische Verbesserungen darstellen, sowie die Ersetzung von Bauteilen durch gleichwertige Teile sind zulässig, soweit sie die Verwendbarkeit zum vertraglich vorgesehenen Zweck nicht beeinträchtigen.</p>
    <p>(5) Der Verkäufer behält sich das Eigentum oder Urheberrecht an allen von ihm abgegebenen Angeboten und Kostenvoranschlägen sowie dem Auftraggeber zur Verfügung gestellten Zeichnungen, Abbildungen, Berechnungen, Prospekten, Katalogen, Modellen, Werkzeugen und anderen Unterlagen und Hilfsmitteln vor. Der Auftraggeber darf diese Gegenstände ohne ausdrückliche Zustimmung des Verkäufers weder als solche noch inhaltlich Dritten zugänglich machen, sie bekannt geben, selbst oder durch Dritte nutzen oder vervielfältigen. Er hat auf Verlangen des Verkäufers diese Gegenstände vollständig an diesen zurückzugeben und eventuell gefertigte Kopien zu vernichten, wenn sie von ihm im ordnungsgemäßen Geschäftsgang nicht mehr benötigt werden oder wenn Verhandlungen nicht zum Abschluss eines Vertrages führen. Ausgenommen hiervon ist die Speicherung elektronisch zur Verfügung gestellter Daten zum Zwecke üblicher Datensicherung.</p>
    <p><strong>§ 3 Preise und Zahlung</strong></p>
    <p>
        (1) Die Preise gelten für den in den Auftragsbestätigungen aufgeführten Leistungs- und Lieferungsumfang. Mehr- oder Sonderleistungen werden gesondert berechnet. Die Preise verstehen<br>
        sich in EURO ab Werk zuzüglich Verpackung, der gesetzlichen Mehrwertsteuer, bei Exportlieferungen Zoll sowie Gebühren und anderer öffentlicher Abgaben.
    </p>
    <p>(2) Soweit den vereinbarten Preisen die Listenpreise des Verkäufers zugrunde liegen und die Lieferung erst mehr als vier Monate nach Vertragsschluss erfolgen soll, gelten die bei Lieferung gültigen Listenpreise des Verkäufers (jeweils abzüglich eines vereinbarten prozentualen oder festen Rabatts).</p>
    <p>(3) Rechnungsbeträge sind innerhalb von dreißig Tagen ohne jeden Abzug zu bezahlen, sofern nicht etwas anderes schriftlich vereinbart ist. Maßgebend für das Datum der Zahlung ist der Eingang beim Verkäufer. Die Zahlung per Scheck ist ausgeschlossen, sofern sie nicht im Einzelfall gesondert vereinbart wird. Leistet der Auftraggeber bei Fälligkeit nicht, so sind die ausstehenden Beträge ab dem Tag der Fälligkeit mit 5 % p. a. zu verzinsen; die Geltendmachung höherer Zinsen und weiterer Schäden im Falle des Verzugs bleibt unberührt.</p>
    <p>(4) Die Aufrechnung mit Gegenansprüchen des Auftraggebers oder die Zurückbehaltung von Zahlungen wegen solcher Ansprüche ist nur zulässig, soweit die Gegenansprüche unbestritten oder rechtskräftig festgestellt sind.</p>
    <p>(5) Der Verkäufer ist berechtigt, noch ausstehende Lieferungen oder Leistungen nur gegen Vorauszahlung oder Sicherheitsleistung auszuführen oder zu erbringen, wenn ihm nach Abschluss des Vertrages Umstände bekannt werden, welche die Kreditwürdigkeit des Auftraggebers wesentlich zu mindern geeignet sind und durch welche die Bezahlung der offenen Forderungen des Verkäufers durch den Auftraggeber aus dem jeweiligen Vertragsverhältnis (einschließlich aus anderen Einzelaufträgen, für die derselbe Rahmenvertrag gilt) gefährdet wird.</p>
    <p>(6) Für den Fall, dass nach Vertragsschluss die vom Auftragnehmer zu zahlenden Netto-Einkaufspreise für die vertragsgegenständlichen Materialien = (insbesondere Holz, Dämmstoffe, Metalle) zum Zeitpunkt ihrer Lieferung um mehr als 3% Prozent steigen oder fallen sollten, hat jede der beiden Vertragsparteien das Recht, von der jeweils anderen den Eintritt in ergänzende Verhandlungen zu verlangen, mit dem Ziel, durch Vereinbarung eine angemessene Anpassung der vertraglich vereinbarten Preise für die betroffenen vertragsgegenständlichen Materialien an die aktuellen Lieferpreise herbeizuführen.</p>
    <p><strong>§ 4 Lieferung und Lieferzeit</strong></p>
    <p>(1) Lieferungen erfolgen ab Werk.</p>
    <p>(2) Vom Verkäufer in Aussicht gestellte Fristen und Termine für Lieferungen und Leistungen gelten stets nur annähernd, es sei denn, dass ausdrücklich eine feste Frist oder ein fester Termin zugesagt oder vereinbart ist. Sofern Versendung vereinbart wurde, beziehen sich Lieferfristen und Liefertermine auf den Zeitpunkt der Übergabe an den Spediteur, Frachtführer oder sonst mit dem Transport beauftragten Dritten.</p>
    <p>(3) Der Verkäufer kann – unbeschadet seiner Rechte aus Verzug des Auftraggebers – vom Auftraggeber eine Verlängerung von Liefer- und Leistungsfristen oder eine Verschiebung von Liefer- und Leistungsterminen um den Zeitraum verlangen, in dem der Auftraggeber seinen vertraglichen Verpflichtungen dem Verkäufer gegenüber nicht nachkommt.</p>
    <p>(4) Der Verkäufer haftet nicht für Unmöglichkeit der Lieferung oder für Lieferverzögerungen, soweit diese durch höhere Gewalt oder sonstige, zum Zeitpunkt des Vertragsabschlusses nicht vorhersehbare Ereignisse (zB. Betriebsstörungen aller Art, Schwierigkeiten in der Material- oder Energiebeschaffung, Transportverzögerungen, Streiks, rechtmäßige Aussperrungen, Mangel an Arbeitskräften, Energie oder Rohstoffen, Schwierigkeiten bei der Beschaffung von notwendigen behördlichen Genehmigungen, behördliche Maßnahmen oder die ausbleibende, nicht richtige oder nicht rechtzeitige Belieferung durch Lieferanten) verursacht worden sind, die der Verkäufer nicht zu vertreten hat. Sofern solche Ereignisse dem Verkäufer die Lieferung oder Leistung wesentlich erschweren oder unmöglich machen und die Behinderung nicht nur von vorübergehender Dauer ist, ist der Verkäufer zum Rücktritt vom Vertrag berechtigt. Bei Hindernissen vorübergehender Dauer verlängern sich die Liefer- oder Leistungsfristen oder verschieben sich die Liefer- oder Leistungstermine um den Zeitraum der Behinderung zuzüglich einer angemessenen Anlauffrist. Soweit dem Auftraggeber infolge der Verzögerung die Abnahme der Lieferung oder Leistung nicht zuzumuten ist, kann er durch unverzügliche schriftliche Erklärung gegenüber dem Verkäufer vom Vertrag zurücktreten.</p>
    <p>(5) Der Verkäufer ist nur zu Teillieferungen berechtigt, wenn</p>
    <ul>
        <li>die Teillieferung für den Auftraggeber im Rahmen des vertraglichen Bestimmungszwecks verwendbar ist,</li>
        <li>die Lieferung der restlichen bestellten Ware sichergestellt ist und</li>
        <li>dem Auftraggeber hierdurch kein erheblicher Mehraufwand oder zusätzliche Kosten entstehen (es sei denn, der Verkäufer erklärt sich zur Übernahme dieser Kosten bereit).</li>
    </ul>
    <p>(6) Gerät der Verkäufer mit einer Lieferung oder Leistung in Verzug oder wird ihm eine Lieferung oder Leistung, gleich aus welchem Grunde, unmöglich, so ist die Haftung des Verkäufers auf Schadensersatz nach Maßgabe des § 8 dieser Allgemeinen Lieferbedingungen beschränkt.</p>
    <p><strong>§ 5 Erfüllungsort, Versand, Verpackung, Gefahrübergang, Abnahme</strong></p>
    <p>(1) Erfüllungsort für alle Verpflichtungen aus dem Vertragsverhältnis ist Calw, soweit nichts anderes bestimmt ist. Schuldet der Verkäufer auch die Installation, ist Erfüllungsort der Ort, an dem die Installation zu erfolgen hat.</p>
    <p>(2) Die Versandart und die Verpackung unterstehen dem pflichtgemäßen Ermessen des Verkäufers.</p>
    <p>(3) Die Gefahr geht spätestens mit der Übergabe des Liefergegenstandes (wobei der Beginn des Verladevorgangs maßgeblich ist) an den Spediteur, Frachtführer oder sonst zur Ausführung der Versendung bestimmten Dritten auf den Auftraggeber über. Dies gilt auch dann, wenn Teillieferungen erfolgen oder der Verkäufer noch andere Leistungen (zB. Versand oder Installation) übernommen hat. Verzögert sich der Versand oder die Übergabe infolge eines Umstandes, dessen Ursache beim Auftraggeber liegt, geht die Gefahr von dem Tag an auf den Auftraggeber über, an dem der Liefergegenstand versandbereit ist und der Verkäufer dies dem Auftraggeber angezeigt hat.</p>
    <p>(4) Lagerkosten nach Gefahrübergang trägt der Auftraggeber. Bei Lagerung durch den Verkäufer betragen die Lagerkosten [0,25]% des Rechnungsbetrages der zu lagernden Liefergegenstände pro abgelaufene Woche. Die Geltendmachung und der Nachweis weiterer oder geringerer Lagerkosten bleiben vorbehalten.</p>
    <p>(5) Die Sendung wird vom Verkäufer nur auf ausdrücklichen Wunsch des Auftraggebers und auf dessen Kosten gegen Diebstahl, Bruch-, Transport-, Feuer- und Wasserschäden oder sonstige versicherbare Risiken versichert.</p>
    <p>(6) Soweit eine Abnahme stattzufinden hat, gilt die Kaufsache als abgenommen, wenn</p>
    <ul>
        <li>die Lieferung und, sofern der Verkäufer auch die Installation schuldet, die Installation abgeschlossen ist,</li>
        <li>der Verkäufer dies dem Auftraggeber unter Hinweis auf die Abnahmefiktion nach diesem § 5 (6) mitgeteilt und ihn zur Abnahme aufgefordert hat,</li>
        <li>seit der Lieferung oder Installation [zwölf] Werktage vergangen sind oder der Auftraggeber mit der Nutzung der Kaufsache begonnen hat (zB. die gelieferte Anlage in Betrieb genommen hat) und in diesem Fall seit Lieferung oder Installation [sechs] Werktage vergangen sind und</li>
        <li>der Auftraggeber die Abnahme innerhalb dieses Zeitraums aus einem anderen Grund als wegen eines dem Verkäufer angezeigten Mangels, der die Nutzung der Kaufsache unmöglich macht oder wesentlich beeinträchtigt, unterlassen hat.</li>
    </ul>

    <p><strong>§ 6 Gewährleistung, Sachmängel</strong></p>
    <p>(1) Die Gewährleistungsfrist beträgt ein Jahr ab Lieferung oder, soweit eine Abnahme erforderlich ist, ab der Abnahme. Diese Frist gilt nicht für Schadensersatzansprüche des Auftraggebers aus der Verletzung des Lebens, des Körpers oder der Gesundheit oder aus vorsätzlichen oder grob fahrlässigen Pflichtverletzungen des Verkäufers oder seiner Erfüllungsgehilfen, welche jeweils nach den gesetzlichen Vorschriften verjähren.</p>
    <p>(2) Die gelieferten Gegenstände sind unverzüglich nach Ablieferung an den Auftraggeber oder an den von ihm bestimmten Dritten sorgfältig zu untersuchen. Sie gelten hinsichtlich offensichtlicher Mängel oder anderer Mängel, die bei einer unverzüglichen, sorgfältigen Untersuchung erkennbar gewesen wären, als vom Käufer genehmigt, wenn dem Verkäufer nicht binnen sieben Werktagen nach Ablieferung eine schriftliche Mängelrüge zugeht. Hinsichtlich anderer Mängel gelten die Liefergegenstände als vom Käufer genehmigt, wenn die Mängelrüge dem Verkäufer nicht binnen sieben Werktagen nach dem Zeitpunkt zugeht, in dem sich der Mangel zeigte; war der Mangel für den Auftraggeber bei normaler Verwendung bereits zu einem früheren Zeitpunkt erkennbar, ist jedoch dieser frühere Zeitpunkt für den Beginn der Rügefrist maßgeblich. Auf Verlangen des Verkäufers ist ein beanstandeter Liefergegenstand frachtfrei an den Verkäufer zurückzusenden. Bei berechtigter Mängelrüge vergütet der Verkäufer die Kosten des günstigsten Versandweges; dies gilt nicht, soweit die Kosten sich erhöhen, weil der Liefergegenstand sich an einem anderen Ort als dem Ort des bestimmungsgemäßen Gebrauchs befindet.</p>
    <p>(3) Bei Sachmängeln der gelieferten Gegenstände ist der Verkäufer nach seiner innerhalb angemessener Frist zu treffenden Wahl zunächst zur Nachbesserung oder Ersatzlieferung verpflichtet und berechtigt. Im Falle des Fehlschlagens, dh. der Unmöglichkeit, Unzumutbarkeit, Verweigerung oder unangemessenen Verzögerung der Nachbesserung oder Ersatzlieferung, kann der Auftraggeber vom Vertrag zurücktreten oder den Kaufpreis angemessen mindern.</p>
    <p>(4) Beruht ein Mangel auf dem Verschulden des Verkäufers, kann der Auftraggeber unter den in § 8 bestimmten Voraussetzungen Schadensersatz verlangen.</p>
    <p>(5) Bei Mängeln von Bauteilen anderer Hersteller, die der Verkäufer aus lizenzrechtlichen oder tatsächlichen Gründen nicht beseitigen kann, wird der Verkäufer nach seiner Wahl seine Gewährleistungsansprüche gegen die Hersteller und Lieferanten für Rechnung des Auftraggebers geltend machen oder an den Auftraggeber abtreten. Gewährleistungsansprüche gegen den Verkäufer bestehen bei derartigen Mängeln unter den sonstigen Voraussetzungen und nach Maßgabe dieser Allgemeinen Lieferbedingungen nur, wenn die gerichtliche Durchsetzung der vorstehend genannten Ansprüche gegen den Hersteller und Lieferanten erfolglos war oder, beispielsweise aufgrund einer Insolvenz, aussichtslos ist. Während der Dauer des Rechtsstreits ist die Verjährung der betreffenden Gewährleistungsansprüche des Auftraggebers gegen den Verkäufer gehemmt.</p>
    <p>(6) Die Gewährleistung entfällt, wenn der Auftraggeber ohne Zustimmung des Verkäufers den Liefergegenstand ändert oder durch Dritte ändern lässt und die Mängelbeseitigung hierdurch unmöglich oder unzumutbar erschwert wird. In jedem Fall hat der Auftraggeber die durch die Änderung entstehenden Mehrkosten der Mängelbeseitigung zu tragen.</p>
    <p>(7) Eine im Einzelfall mit dem Auftraggeber vereinbarte Lieferung gebrauchter Gegenstände erfolgt unter Ausschluss jeglicher Gewährleistung für Sachmängel</p>
    <p><strong>§ 7 Schutzrechte</strong></p>
    <p>(1) Der Verkäufer steht nach Maßgabe dieses § 7 dafür ein, dass der Liefergegenstand frei von gewerblichen Schutzrechten oder Urheberrechten Dritter ist. Jeder Vertragspartner wird den anderen Vertragspartner unverzüglich schriftlich benachrichtigen, falls ihm gegenüber Ansprüche wegen der Verletzung solcher Rechte geltend gemacht werden.</p>
    <p>(2) In dem Fall, dass der Liefergegenstand ein gewerbliches Schutzrecht oder Urheberrecht eines Dritten verletzt, wird der Verkäufer nach seiner Wahl und auf seine Kosten den Liefergegenstand derart abändern oder austauschen, dass keine Rechte Dritter mehr verletzt werden, der Liefergegenstand aber weiterhin die vertraglich vereinbarten Funktionen erfüllt, oder dem Auftraggeber durch Abschluss eines Lizenzvertrages das Nutzungsrecht verschaffen. Gelingt dem Verkäufer dies innerhalb eines angemessenen Zeitraums nicht, ist der Auftraggeber berechtigt, von dem Vertrag zurückzutreten oder den Kaufpreis angemessen zu mindern. Etwaige Schadensersatzansprüche des Auftraggebers unterliegen den Beschränkungen des § 8 dieser Allgemeinen Lieferbedingungen.</p>
    <p>(3) Bei Rechtsverletzungen durch vom Verkäufer gelieferte Produkte anderer Hersteller wird der Verkäufer nach seiner Wahl seine Ansprüche gegen die Hersteller und Vorlieferanten für Rechnung des Auftraggebers geltend machen oder an den Auftraggeber abtreten. Ansprüche gegen den Verkäufer bestehen in diesen Fällen nach Maßgabe dieses § 7 nur, wenn die gerichtliche Durchsetzung der vorstehend genannten Ansprüche gegen die Hersteller und Vorlieferanten erfolglos war oder, beispielsweise aufgrund einer Insolvenz, aussichtslos ist.</p>
    <p><strong>§ 8 Haftung auf Schadensersatz wegen Verschuldens</strong></p>
    <p>(1) Die Haftung des Verkäufers auf Schadensersatz, gleich aus welchem Rechtsgrund, insbesondere aus Unmöglichkeit, Verzug, mangelhafter oder falscher Lieferung, Vertragsverletzung, Verletzung von Pflichten bei Vertragsverhandlungen und unerlaubter Handlung ist, soweit es dabei jeweils auf ein Verschulden ankommt, nach Maßgabe dieses § 8 eingeschränkt.</p>
    <p>(2) Der Verkäufer haftet nicht im Falle einfacher Fahrlässigkeit seiner Organe, gesetzlichen Vertreter, Angestellten oder sonstigen Erfüllungsgehilfen, soweit es sich nicht um eine Verletzung vertragswesentlicher Pflichten handelt. Vertragswesentlich sind die Verpflichtung zur rechtzeitigen Lieferung und Installation des Liefergegenstands, dessen Freiheit von Rechtsmängeln sowie solchen Sachmängeln, die seine Funktionsfähigkeit oder Gebrauchstauglichkeit mehr als nur unerheblich beeinträchtigen, sowie Beratungs-, Schutz- und Obhutspflichten, die dem Auftraggeber die vertragsgemäße Verwendung des Liefergegenstands ermöglichen sollen oder den Schutz von Leib oder Leben von Personal des Auftraggebers oder den Schutz von dessen Eigentum vor erheblichen Schäden bezwecken.</p>
    <p>(3) Soweit der Verkäufer gemäß § 8 (2) dem Grunde nach auf Schadensersatz haftet, ist diese Haftung auf Schäden begrenzt, die der Verkäufer bei Vertragsschluss als mögliche Folge einer Vertragsverletzung vorausgesehen hat oder die er bei Anwendung verkehrsüblicher Sorgfalt hätte voraussehen müssen. Mittelbare Schäden und Folgeschäden, die Folge von Mängeln des Liefergegenstands sind, sind außerdem nur ersatzfähig, soweit solche Schäden bei bestimmungsgemäßer Verwendung des Liefergegenstands typischerweise zu erwarten sind.</p>
    <p>(4) Im Falle einer Haftung für einfache Fahrlässigkeit ist die Ersatzpflicht des Verkäufers für Sachschäden und daraus resultierende weitere Vermögensschäden auf einen Betrag von EUR 1 Mio. je Schadensfall (entsprechend der derzeitigen Deckungssumme seiner Produkthaftpflichtversicherung oder Haftpflichtversicherung) beschränkt, auch wenn es sich um eine Verletzung vertragswesentlicher Pflichten handelt.</p>
    <p>(5) Die vorstehenden Haftungsausschlüsse und -beschränkungen gelten in gleichem Umfang zugunsten der Organe, gesetzlichen Vertreter, Angestellten und sonstigen Erfüllungsgehilfen des Verkäufers.</p>
    <p>(6) Soweit der Verkäufer technische Auskünfte gibt oder beratend tätig wird und diese Auskünfte oder Beratung nicht zu dem von ihm geschuldeten, vertraglich vereinbarten Leistungsumfang gehören, geschieht dies unentgeltlich und unter Ausschluss jeglicher Haftung.</p>
    <p>(7) Die Einschränkungen dieses § 8 gelten nicht für die Haftung des Verkäufers wegen vorsätzlichen Verhaltens, für garantierte Beschaffenheitsmerkmale, wegen Verletzung des Lebens, des Körpers oder der Gesundheit oder nach dem Produkthaftungsgesetz.</p>
    <p><strong>§ 9 Eigentumsvorbehalt</strong></p>
    <p>(1) Der nachfolgend vereinbarte Eigentumsvorbehalt dient der Sicherung aller jeweils bestehenden derzeitigen und künftigen Forderungen des Verkäufers gegen den Käufer aus der zwischen den Vertragspartnern bestehenden Lieferbeziehung über (einschließlich Saldoforderungen aus einem auf diese Lieferbeziehung beschränkten Kontokorrentverhältnis).</p>
    <p>(2) Die vom Verkäufer an den Käufer gelieferte Ware bleibt bis zur vollständigen Bezahlung aller gesicherten Forderungen Eigentum des Verkäufers. Die Ware sowie die nach den nachfolgenden Bestimmungen an ihre Stelle tretende, vom Eigentumsvorbehalt erfasste Ware wird nachfolgend „Vorbehaltsware“ genannt.</p>
    <p>(3) Der Käufer verwahrt die Vorbehaltsware unentgeltlich für den Verkäufer.</p>
    <p>(4) Der Käufer ist berechtigt, die Vorbehaltsware bis zum Eintritt des Verwertungsfalls (Absatz 9) im ordnungsgemäßen Geschäftsverkehr zu verarbeiten und zu veräußern. Verpfändungen und Sicherungsübereignungen sind unzulässig.</p>
    <p>(5) Wird die Vorbehaltsware vom Käufer verarbeitet, so wird vereinbart, dass die Verarbeitung im Namen und für Rechnung des Verkäufers als Hersteller erfolgt und der Verkäufer unmittelbar das Eigentum oder – wenn die Verarbeitung aus Stoffen mehrerer Eigentümer erfolgt oder der Wert der verarbeiteten Sache höher ist als der Wert der Vorbehaltsware – das Miteigentum (Bruchteilseigentum) an der neu geschaffenen Sache im Verhältnis des Werts der Vorbehaltsware zum Wert der neu geschaffenen Sache erwirbt. Für den Fall, dass kein solcher Eigentumserwerb beim Verkäufer eintreten sollte, überträgt der Käufer bereits jetzt sein künftiges Eigentum oder – im og. Verhältnis – Miteigentum an der neu geschaffenen Sache zur Sicherheit an den Verkäufer. Wird die Vorbehaltsware mit anderen Sachen zu einer einheitlichen Sache verbunden oder untrennbar vermischt und ist eine der anderen Sachen als Hauptsache anzusehen, so überträgt der Verkäufer, soweit die Hauptsache ihm gehört, dem Käufer anteilig das Miteigentum an der einheitlichen Sache in dem in Satz 1 genannten Verhältnis.</p>
    <p>(6) Im Fall der Weiterveräußerung der Vorbehaltsware tritt der Käufer bereits jetzt sicherungshalber die hieraus entstehende Forderung gegen den Erwerber – bei Miteigentum des Verkäufers an der Vorbehaltsware anteilig entsprechend dem Miteigentumsanteil – an den Verkäufer ab. Gleiches gilt für sonstige Forderungen, die an die Stelle der Vorbehaltsware treten oder sonst hinsichtlich der Vorbehaltsware entstehen, wie zB. Versicherungsansprüche oder Ansprüche aus unerlaubter Handlung bei Verlust oder Zerstörung. Der Verkäufer ermächtigt den Käufer widerruflich, die an den Verkäufer abgetretenen Forderungen im eigenen Namen einzuziehen. Der Verkäufer darf diese Einzugsermächtigung nur im Verwertungsfall widerrufen.</p>
    <p>(7) Greifen Dritte auf die Vorbehaltsware zu, insbesondere durch Pfändung, wird der Käufer sie unverzüglich auf das Eigentum des Verkäufers hinweisen und den Verkäufer hierüber informieren, um ihm die Durchsetzung seiner Eigentumsrechte zu ermöglichen. Sofern der Dritte nicht in der Lage ist, dem Verkäufer die in diesem Zusammenhang entstehenden gerichtlichen oder außergerichtlichen Kosten zu erstatten, haftet hierfür der Käufer dem Verkäufer.</p>
    <p>(8) Der Verkäufer wird die Vorbehaltsware sowie die an ihre Stelle tretenden Sachen oder Forderungen freigeben, soweit ihr Wert die Höhe der gesicherten Forderungen um mehr als 50 % übersteigt. Die Auswahl der danach freizugebenden Gegenstände liegt beim Verkäufer.</p>
    <p>(9) Tritt der Verkäufer bei vertragswidrigem Verhalten des Käufers – insbesondere Zahlungsverzug – vom Vertrag zurück (Verwertungsfall), ist er berechtigt, die Vorbehaltsware herauszuverlangen.</p>
    <p><strong>§10 CSR Nachhaltigkeitsanforderungen</strong></p>
    <p>Jeder Lieferant hat sich entsprechend Corporate Social Resposiblity sicherzustellen, dass Menschenrechte, Umweltrichtlinien, Chancengleichheit und Arbeits- und Gesundheitsschutz im eigenen Betrieb und deren Niederlassungen sowie Lieferanten sichergestellt ist.</p>
    <p><strong>§ 11 Schlussbestimmungen</strong></p>
    <p>(1) Ist der Auftraggeber Kaufmann, eine juristische Person des öffentlichen Rechts oder ein öffentlich-rechtliches Sondervermögen oder hat er in der Bundesrepublik Deutschland keinen allgemeinen Gerichtsstand, so ist Gerichtsstand für alle etwaigen Streitigkeiten aus der Geschäftsbeziehung zwischen dem Verkäufer und dem Auftraggeber nach Wahl des Verkäufers Calw (Ort) oder der Sitz des Auftraggebers. Für Klagen gegen den Verkäufer ist in diesen Fällen jedoch Calw (Ort) ausschließlicher Gerichtsstand. Zwingende gesetzliche Bestimmungen über ausschließliche Gerichtsstände bleiben von dieser Regelung unberührt.</p>
    <p>(2) Die Beziehungen zwischen dem Verkäufer und dem Auftraggeber unterliegen ausschließlich dem Recht der Bundesrepublik Deutschland. Das Übereinkommen der Vereinten Nationen über Verträge über den internationalen Warenkauf vom 11. April 1980 (CISG) gilt nicht.</p>
    <p>
        (3) Soweit der Vertrag oder diese Allgemeinen Lieferbedingungen Regelungslücken enthalten, gelten zur Ausfüllung dieser Lücken diejenigen rechtlich wirksamen Regelungen als vereinbart, welche die Vertragspartner nach den wirtschaftlichen Zielsetzungen des Vertrages und dem Zweck dieser Allgemeinen Lieferbedingungen vereinbart hätten, wenn sie die Regelungslücke gekannt hätten.<br>
        Hinweis:<br>
        Der Auftraggeber nimmt davon Kenntnis, dass der Verkäufer Daten aus dem Vertragsverhältnis nach § 28 Bundesdatenschutzgesetz zum Zwecke der Datenverarbeitung speichert und sich das Recht vorbehält, die Daten, soweit für die Vertragserfüllung erforderlich, Dritten (zB. Versicherungen) zu übermitteln.
    </p>
    <p>Stand: Mai 2019</p>
</section>
@endsection
